import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import ContainerNavbar from "@/common/ContainerNavbar";
import ReduxProvider from "@/ReduxProvider/ReduxProvider";
import { Bounce, ToastContainer } from "react-toastify";
import { SocketProvider } from "@/context/SocketContext";
import { cookies } from "next/headers";
import IncomingCallModal from "@/components/IncomingCallModal";
import CallWindow from "@/components/CallWindow";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("whatsApp")?.value;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SocketProvider initialToken={token}>
            {children}
            <IncomingCallModal />
            <CallWindow />
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              transition={Bounce}
            />{" "}
          </SocketProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
